apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training-logs
  template:
    metadata:
      labels:
        app: training-logs
    spec:
      containers:
      - name: training-logs
        image: chadtsigler/training-data:v1.0
        env:
        - name: FILE_PATH
          value: /logs/test.log
        volumeMounts:
        - name: log-data
          mountPath: /logs
  volumes:
  - name: log-data
    hostPath:
      path: /var/logdata 
